version: '3'
services:
  service-registry:
    image: service-registry:latest
    container_name: service-registry
    ports:
      - "8056:8056"
    networks:
      - springboot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8056/actuator/health"]
      interval: 4s
      timeout: 5s
      retries: 2

  customer-service:
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network

  account-service:
    image: account-service:latest
    container_name: account-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network

  movement-service:
    image: movement-service:latest
    container_name: movement-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network

  customer-middleend:
    image: customer-middleend:latest
    container_name: customer-middleend
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network

  account-middleend:
    image: account-middleend:latest
    container_name: account-middleend
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network

  movement-middleend:
    image: movement-middleend:latest
    container_name: movement-middleend
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/v1/actuator/health"]
      interval: 2s
      timeout: 5s
      retries: 6
    networks:
      - springboot-network
    

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8056/eureka/
    networks:
      - springboot-network
    depends_on:
      service-registry:
        condition: service_healthy
      customer-service:
        condition: service_healthy

networks:
  springboot-network:
    driver: bridge