server:
  servlet:
    context-path: /api/v1
  port: 8084


spring:
  ## application name
  application:
    name: customer-service
  ## database config H2
  datasource:
    url: jdbc:h2:mem:custumerdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  ## H2 console config
  h2:
    console:
      enabled: true
      path: /h2-console
  ## jpa structure config
  jpa:
    show-sql: true
    format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8056/eureka/